### ISSUE TITLE
Add stop and restart functions

### ISSUE THREAD

**Issue by gizmo693** [spiculedata/openldap-charm#1]
Should start and stop the OpenLDAP daemon

**Comment by buggtb** [comment]
Stop isn't required, but the new snap doesn't require a specific start because it is a daemon. This means to start or stop or restart you need to provide:

    service snap.openldap.slapd start/stop/restart

So for example, on configuration change that requires a restart:

    service snap.openldap.slapd restart

As such:

https://github.com/spiculedata/openldap-charm/blob/master/reactive/openldap.py#L15-L21 

    check_output(['openldap.slapd-config'])

is no longer required.
